d-apache2-openssl:
  ports:
  - 65500:22/tcp
  - 65501:80/tcp
  - 65502:443/tcp
  environment:
    DWL_LOCAL: en_US.UTF-8
    DWL_USER_NAME: username
    DWL_USER_PASSWD: secret
    DWL_SSH_ACCESS: false
    DWL_USER_DNS: dev.davaskweblimited.com
    DWL_USER_APACHE_CONF: default-ssl
    DWL_SSLKEY_C: EU
    DWL_SSLKEY_ST: France
    DWL_SSLKEY_L: Vannes
    DWL_SSLKEY_O: davask web limited - docker container
    DWL_SSLKEY_CN: davaskweblimited.com
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: dwl=dwlComPrivate
  tty: true
  hostname: dev.davaskweblimited.com
  image: davask/d-apache-openssl2:2.4-u14.04
  volumes:
  - /path/to/proxy/sites-available:/etc/apache2/sites-available
  - /path/to/files:/home/username/files
  stdin_open: true
